# Generated by Django 4.1.7 on 2023-05-23 21:04

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('NIT', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=100)),
                ('fechaFundacion', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('paginaWeb', models.CharField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
                ('direccion', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googleApp.ciudades')),
                ('especialidades', models.ManyToManyField(to='googleApp.especialidades')),
                ('servicios', models.ManyToManyField(to='googleApp.servicios')),
            ],
            options={
                'db_table': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('experienciaCargo', models.CharField(default='1', max_length=100)),
                ('tipoDoc', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('experiencia', models.IntegerField(default=0)),
                ('videoEntrevista', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('imagen', models.TextField(default='n')),
                ('entrevista', models.TextField(default='n')),
                ('permiso', models.TextField(default='n')),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googleApp.empresas')),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
    ]
