# Generated by Django 4.0.5 on 2023-04-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googleApp', '0002_ciudades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='ciudad',
            field=models.ForeignKey(default='d', on_delete=django.db.models.deletion.CASCADE, to='google.ciudades'),
        ),
    ]
