# Generated by Django 4.0.5 on 2023-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleApp', '0005_alter_empresas_fechafundacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='fechaFundacion',
            field=models.DateField(),
        ),
    ]
