# Generated by Django 4.1.7 on 2023-05-23 14:42

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('googleApp', '0012_rename__id_usuarios_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Servicios',
            },
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleados',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googleApp.empresas'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googleApp.ciudades'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='especialidades',
            field=models.ManyToManyField(to='googleApp.especialidades'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='servicios',
            field=models.ManyToManyField(to='googleApp.servicios'),
        ),
    ]
