from .views import *
from django.urls import path, include
from googleApp import views as view
'La página define las rutas y direcciones URL del proyecto. Cada ruta especifica una URL y la función de vista asociada que se ejecutará cuando se acceda a esa URL en el navegador.'
urlpatterns = [
   path('', view.vistaBase, name='inicio'),
   path('registro/', view.registro, name='registro'),
   path('login/', view.login, name='login'),
   path('logout/', view.logout_view, name='logout'),
   path('home',view.home, name="home"),
   path('geocode',view.geocode, name="geocode"),
   path('geocode/club/<int:pk>',view.geocode_club, name="geocode_club"),
   path('geocode_sede/club/<str:pk>', view.geocode_club_sede, name="geocode_club_sede"),
   path('mapa/',view.mapa, name="map"),
   path('mapa_sede/', view.mapa_sede, name="map_sede"),
   path('mydata',view.mydata, name="mydata"),
   path('obtener_Ser_Esp/',view.obtener_Ser_Esp, name="obtener_Ser_Esp"),
   path('crearEmpresa', view.crearEmpresa, name='crearEmpresa'),
   path('editarEmpresa/<NIT>', view.editarEmpresa, name='editarEmpresa'),
   path('inactivarEmpresa/<NIT>', view.inactivarEmpresa, name='inactivarEmpresa'),
   path('crearSede/<str:rest>', view.crearSede, name='crearSede'),
   path('editarSede/<nombre>', view.editarSede, name='editarSede'),
   path('inactivarSede/<nombre>', view.inactivarSede, name='inactivarSede'),
   path('listaEmp/<str:rest>/', view.vistaListaEmpl, name='listaEmp'),
   path('crearEmp/<str:rest>/', view.vistaCrearEmpl, name='crearEmp'),
   path('editarEmp/<str:rest>/<str:ced>/', view.vistaEditarEmpl, name='editarEmp'),
   path('verEmp/<str:rest>/<str:ced>/', view.vistaVerEmpl, name='verEmp'),
   path('estadoEmp/<str:rest>/<str:ced>/', view.estadoEmp, name='estadoEmp'),
   path('mydataBusqueda',view.mydataBusqueda, name="mydataBusqueda"),
   path('servicios-especialidades/', view.servicios_especialidades, name='servicios_especialidades'),
   path('crear-servicio/', view.crearServicio, name='crear_servicio'),
   path('editar-servicio/<str:servicio_id>', view.editarServicio, name='editar_servicio'),
   path('eliminar-servicio/<str:servicio_id>', view.eliminarServicio, name='eliminar_servicio'),
   path('especialidades/', view.especialidades, name='especialidades'),
   path('crear-especialidades/', view.crearEspecialidad, name='crear_especialidades'),
   path('editar-especialidad/<str:servicio_id>', view.editarEspecialidad, name='editar_especialidad'),
   path('eliminar-especialidad/<str:servicio_id>', view.eliminarEspecialidad, name='eliminar_especialidad'),
   path('listaEmp/', view.vistaListaEmplTodos, name='vistaListaEmplTodos'),
   path('mapaEmp/<str:rest>',view.mapaEmp, name="mapaEmp"),
]