# Generated by Django 4.0.5 on 2023-04-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('NIT', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=100)),
                ('fechaFundacion', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('paginaWeb', models.CharField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
                ('direccion', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'Empresas',
            },
        ),
    ]
