# Generated by Django 4.0.5 on 2023-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0003_empresas_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='mision',
            field=models.TextField(default='mision'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='vision',
            field=models.TextField(default='vision'),
        ),
    ]
