# Generated by Django 4.0.5 on 2023-04-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0004_empresas_mision_empresas_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='fechaFundacion',
            field=models.DateTimeField(),
        ),
    ]
