# Generated by Django 2.2.14 on 2023-04-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0006_alter_empresas_fechafundacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google.Ciudades'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='mision',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='vision',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipoDoc', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('experiencia', models.IntegerField(default=0)),
                ('videoEntrevista', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google.Empresas')),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
    ]
