# Generated by Django 4.0.5 on 2023-04-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0006_alter_empresas_fechafundacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google.ciudades'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='mision',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='vision',
            field=models.TextField(),
        ),
    ]
