# Generated by Django 2.2.14 on 2023-04-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0007_auto_20230423_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='imagen',
            field=models.TextField(default='n'),
        ),
    ]
