# Generated by Django 4.1.8 on 2023-04-23 02:43

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0007_alter_empresas_ciudad_alter_empresas_mision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google.empresas')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google.ciudades')),
            ],
            options={
                'db_table': 'Sedes',
            },
        ),
    ]
