# Generated by Django 4.1.7 on 2023-04-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0009_empleados_usuarios_delete_sedes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
