# Generated by Django 2.2.14 on 2023-04-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0010_auto_20230423_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='img',
        ),
    ]
