# Generated by Django 2.2.14 on 2023-04-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0011_remove_empleados_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='entrevista',
            field=models.TextField(default='n'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='permiso',
            field=models.TextField(default='n'),
        ),
    ]
