# Generated by Django 4.1.7 on 2023-04-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0011_alter_usuarios__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='_id',
            new_name='id',
        ),
    ]
