# Generated by Django 2.2.14 on 2023-04-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0012_auto_20230423_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='email2',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
