# Generated by Django 2.2.14 on 2023-04-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0013_empleados_email2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='email2',
            new_name='cargoExp',
        ),
    ]
