# Generated by Django 2.2.14 on 2023-04-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0014_auto_20230423_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='cargoExp',
        ),
    ]
