# Generated by Django 2.2.14 on 2023-04-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0015_remove_empleados_cargoexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='experienciaCargo',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
